FROM node:20

# 作業ディレクトリ
WORKDIR /app

# package.json だけ先にコピー（キャッシュ効かせる）
COPY package*.json ./

# 依存関係インストール
RUN npm install

# ソースをコピー
COPY . .

# Vite のポート
EXPOSE 5173

# 開発サーバー起動
CMD ["npm", "run", "dev", "--", "--host"]