FROM php:8.4

# 作業ディレクトリ
WORKDIR /var/www/html

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    curl \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl pdo_mysql gd

# Composer をインストール
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Laravel の権限対策
RUN chown -R www-data:www-data /var/www

# ポート（artisan serve 用）
EXPOSE 8000

# コンテナ起動時のコマンド
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]